### ISSUE TITLE
API Workshop:  June 12, 2023

### ISSUE THREAD

**Issue by RinatS** [im-customers/intel#42]
Add the contact info below:

- First Name/Last Name
- Business email address
- Role in customer org

**Comment by RinatS** [comment]
Rinat Shagisultanov
Tech Director
rinats@infomagnus.com

**Comment by pbhutori** [comment]
Pankaj Bhutoria
pankaj.bhutoria@intel.com
Infrastructure and DevOps Engineer

**Comment by jchave2330** [comment]
Jorge Chaves
DevOps engineer
jorge.chaves.romero@intel.com

**Comment by jsaenzg394** [comment]
Jose Saenz
jose.saenz.gairaud@intel.com
DevOps Engineer

**Comment by irehanshikkalgar** [comment]
Rehan Shikkalgar
rehan.shikkalgar@intel.com
Software Engineer
